### ISSUE TITLE
Upload to Hackage

### ISSUE THREAD

**Issue by etherz10** [iconnect/rails-session#16]
@mcfilib Hey dude, following https://github.com/iconnect/rails-session/pull/15 this now builds on GHC 8.6.5, 8.8.4 and 8.10.7 but it's not available via Hackage.

Can you either upload it for me or add me as a maintainer and I can do it.

**Comment by philipcunningham** [comment]
thanks @etherz10 🙇 

my development environment isn't currently setup to do haskell work but i'll aim to get this released on hackage soon.

**Comment by mcfilib** [comment]
@etherz10 i think it would probably make more sense if i transfer ownership to someone at iris connect instead. can you let me know which user account i should assign this to? feel free to drop me an email if you prefer.

/cc @cdornan

**Comment by philipcunningham** [comment]
@etherz10 i think it would sense for me to transfer ownership to someone at irisconnect. i've added @adinapoli and @cdornan as maintainers on hackage. i don't have your hackage but they should be able to add you as maintainer.

**Comment by philipcunningham** [comment]
@etherz10 please close this issue once you're set up to publish new releases to hackage 🙇
