### ISSUE TITLE
Support JSON serialization

### ISSUE THREAD

**Issue by etherz10** [iconnect/rails-session#18]
Rails 7 defaults to using JSON serialization instead of Marshal like Rails 5 did, thus this package will fail to decode session cookies.

**Comment by adinapoli** [comment]
@etherz10 I hopelessly forgot everything about this, as Philip was the main driver about the effort. Where can I read more about Rails' serialisation format?

EDIT: Not sure if that's an option to buy time, but apparently it's possible to use:

```
Rails.application.config.action_dispatch.cookies_serializer = :hybrid
```

Which should allow for both Marshal and JSON to co-exist?
